### ISSUE TITLE
Exported headparts SkyrimSE crashes game

### ISSUE THREAD

**Issue by LittleMissF** [BadDogSkyrim/PyNifly#123]
Hi there!

I have a new issue and panic a bit atm, because I am mainly modding headparts. Exporting headparts for Skyrim SE suddenly crashes game. I tried now several headparts, reinstalled blender, tried different versions(2.93.1, 3.0, 3.3) different plug-in versions, reinstalled plug-ins. The only thing I didn’t do is reinstalling my pythons. I asked now if someone in the modding community I am in could export a headpart for me and I see if it’s crashing, too. See if the error is reproduced. I know I post this probably wrong, but my brain isn’t working so well in my panic.

Greets Frannie

edit: Update, Rage made me aware of the tri files needed to be loaded in. Now it works but that’s increasing workflow so much. It worked fine in the past. Did I just get away with it? I am glad I can still work with headparts. Your plug-in is such a god send. I am relieved. I am thou still a bit confused. (I am autistic and this was causing my brain to melt, sorry, I am still in fight and flight mode. So I am probably rambling and talk confused.)

edit2: testing atm some headparts. I saw that the chargen tris for the female head for high poly(probably vanilla then too), gets exported with an _. That’s wrong, it has to be femaleheadchargen, not femalehead_chargen. :) Just As Info.

**Comment by BadDogSkyrim** [comment]
When things go wrong, sit down, take a deep breath and don't do anything fast. Get slow and deliberate.

I've built plenty of heads for SE with this tool, so it's gonna work. We just need to figure out your issue.

The issue with tri files is that they have to match the head exactly. On LE it would just deform but on SE it crashes the game. In addition, deformable head parts have to use a different nif node type. (It's documented in the wiki somewhere.)

So the main thing is your nif and tri have to match whatever you told the game to expect in the head part record. You set up the chargen and expression morphs as shape keys in Blender and then they get exported with the head. Always use those and you'll never have a problem. If you use the head from Blender but the old tris there might be a mismatch.

Chargen tri files can be named whatever you like. The exporter uses "_chargen" because that's standard for at least some heads in some game. You can rename the files.

**Comment by BadDogSkyrim** [comment]
Closing because I don't think this is a bug.
