### ISSUE TITLE
Deformation on facebones head import

### ISSUE THREAD

**Issue by BadDogSkyrim** [BadDogSkyrim/PyNifly#131]
deformation of chin in blender after importing vanilla BaseFemaleHead_faceBones.nif

**Comment by podvornyakva** [comment]
Still having a issue. BaseFemaleHead_faceBone mesh exports in 4/5 of original file size. Jaw and chin looks like it is men's head mesh. Probably i should check it out, by exporting it as BaseMaleHead_faceBones.nif and look in to game representation.

**Comment by podvornyakva** [comment]
Meanwhile i've installed 6.5 version of importer and have imported and exported back faceBones mesh. It is fit to other meshes as it should. No gaps and deformations.

**Comment by BadDogSkyrim** [comment]
So I just tried importing the female base head mesh, then the facebones mesh. The two lie on top of each other vert-for-vert. Where is the deformation you're seeing?

**Comment by podvornyakva** [comment]
I'm telling that i used a 6.5 version. And same BaseFemaleHead_faceBones.nif importrd twice - with "apply skin" and without. One, with "apply skin", is deformed. Upon export fits other meshes right.

**Comment by podvornyakva** [comment]
Not only chin/jaw bone. Also forehead bone and other. I'll make a demonstration of that tomorrow. For now i am struggling with facebones vertex groups.

**Comment by podvornyakva** [comment]
Well. I've noticed strange behavior. If i rename BaseFemaleHead_faceBones.nif to something like Head.nif, upon import mesh is deformed. Well, here is a not deformed mesh looks like in the game. [Notice a gap on forehead to.](https://vk.com/albums289718037?z=photo289718037_457244258%2Fphotos289718037)

**Comment by podvornyakva** [comment]
Hey, man. Good to see you are working on. 7.0 release. Grate! Listen. I have looked in vanilla .txt files in "CharacterAssets" folder and have found information describing "Face_skin" bone, along with "Head_skin" and other. But i get no that bone upon import. I'll try to put that text files to override folder and make all values null, to check - is that affect something. Maybe that how i will find solution...

**Comment by BadDogSkyrim** [comment]
Urgh.

Those text files have to do with the bone morphs CK and the game apply to the head. They define how the head gets modified to make different characters.

So yeah, if the values in there are out of whack, they could change the head shape you see in bad ways.

But they don't affect what's imported from the nif or what's exported back out. I had too many changes stacked up so I closed 7.0 without looking again at this issue. I will in the next few days.

**Comment by podvornyakva** [comment]
Hey. If you need something to be checked/tested - give me a sign.

**Comment by BadDogSkyrim** [comment]
Check out 7.1. There was a bug in the degenerate case where the bone in Blender was parallel to the x-axis. I rewrote the bone transform code (and made it much simpler) and I think it's working correctly now.

**Comment by podvornyakva** [comment]
I can't see 7.1

**Comment by podvornyakva** [comment]
Well. Some glitches still appear on export. Even for vanilla meshes. But it is caused by approximation of values. For mesh with 120 meters size some time appear a +/- 0.000001 - 0.00001 precision error. Even smaller, time to time. For angles and positions. For meshes and bones. Probably it can be fixed by storing new values in to mod that contain "Human Race" definition, from base .esm file. There is also stored an old values of bones and mesh position/rotation.
But for my mesh everything become much better. I've putted alot of time to it. Checked almost every vertex in the mesh. So it just got to be correct. I just need to fix some vertex weight groups. Still cant figureout why is the right eye do not react to facial animations. Checked almost everything. Vanilla mesh working fine but not mine. Strange.

**Comment by BadDogSkyrim** [comment]
I've found a thing in the transforms code that introduced small errors in vertex locations. It's not exactly a bug, it's that when you run enough floating-point calculations errors creep in. I've cleaned up that code and once I get everything put back together it should be faster, more accurate, and do your facebones bones correctly.

Should be soon.

**Comment by BadDogSkyrim** [comment]
Incidentally, surely working on your meshes in blender at 1/10 size will introduce its own errors? Maybe you should work at full size.

**Comment by podvornyakva** [comment]
> Incidentally, surely working on your meshes in blender at 1/10 size will introduce its own errors? Maybe you should work at full size.

Not sure that i understand what do you mean by that. I simply import and export vanilla meshes. Here the [video](https://vk.com/video289718037_456241778?t=32s). What should i size down/up? Every armature and mesh is 1 to 1 size.

**Comment by podvornyakva** [comment]
At last... I did it! No more gaps on seams. Smooth and clean. Have just put all according bones for all skeletons in same position, and it works. Thank you man! Will put new blender file on Nexus soon. Cheers.

**Comment by BadDogSkyrim** [comment]
Glad it worked out.

**Comment by podvornyakva** [comment]
Well. I've deal with skinning, but other problem still exists. Te left eyelids do not move on facial animations, with my mesh. That issue was from beginning. If after beginning of a new game, in character creation menu, i load save game, eyelids facial animations act on both eyes. But after i exit game and load it again, left eyelids stop to move. Don't know what to think. Tomorrow i will make video to demonstrate that issue.

**Comment by podvornyakva** [comment]
Ok. I decided not o bother you with that issue. Probably i've missed some other mesh needed to be redone to achieve complete result. Publication of my mesh is delayed once more. I'd prefer if you made import/export of skeleton, cause nifscope development is stuck for a long time. But i would not insist. Definitely i can solve issues in other way. See you around, man.
