### ISSUE TITLE
Vertex color flag on export if vertices have color data

### ISSUE THREAD

**Issue by megapatato** [BadDogSkyrim/PyNifly#139]
Issue: BSTriShape object with color data on vertices, does not get the "vertex colors" flag set (in Blender, the Object has Object Data with colors for vertices).

To recreate:
1) Import an object that uses vertex colors
e.g. `Skyrim - Meshes0.bsa/meshes/dungeons/caves/green/smallhall/caveghall1way01.nif`
2) Duplicate via Ctrl+D and place somewhere
3) Select all, export to NIF
4) Open in NifSkope to view

![image](https://user-images.githubusercontent.com/60947952/223589275-90313f19-23b6-42f2-8334-a84679fcc0e7.png)
In the attached, the BSTriShape at index 32, it's Vertex Desc. field, does not have the Colors flag.

Desired outcome: the resulting NIF's BSTriShapes have the vertex color flag enabled when the vertices have color data.

**Comment by BadDogSkyrim** [comment]
I just hassled with this myself. IIRC the issue was that Blender has a very confusing way of deciding whether there are vertex colors and even though I could see the color layer in the Blender UI (Color Attributes), I (and the exporter) couldn't see it through the python interface. Eventually I went into vertex paint and that created a layer that worked. I might have had to delete the not-working layer first. 

It might be that I'm not creating the layer properly on import. I'll look at that.

**Comment by megapatato** [comment]
If this is an import problem, https://github.com/BadDogSkyrim/PyNifly/issues/140 may be related. Assuming the incoming NIF declares a BSTriShape to use vertex colors & alphas, then the shader should be using that information too, point at which the plugin can proceed knowing this vertex metadata is present.

**Comment by BadDogSkyrim** [comment]
Fixed in latest.
