### ISSUE TITLE
BSEffectShaderProperty Node - Lighting Influence

### ISSUE THREAD

**Issue by michaelsmolinski** [BadDogSkyrim/PyNifly#190]
Round trip import/export changes BSEffectShaderPropery node's Lighting Influence value from 255 to 0.

Also adds Vertex_Alpha Shader Flag to exported file.

I don't know how/if either of these two items has real in-game impact.

![Untitled](https://github.com/BadDogSkyrim/PyNifly/assets/101998837/d1eaa8e8-935a-470d-8c9a-7f7e25c662e4)

[blackbriarchalet.zip](https://github.com/BadDogSkyrim/PyNifly/files/13553578/blackbriarchalet.zip)

**Comment by BadDogSkyrim** [comment]
I'll check it out. 

VERTEX_ALPHA (and VERTEX_COLOR) are weird because they are set on export depending on whether the exported mesh has vertex color and alpha defined, not based on what's in the shader. (Except indirectly, since it reads those values.) So it's possible to have them set on export when they weren't on import. But if you didn't change anything, they should be consistent.

**Comment by BadDogSkyrim** [comment]
Okay, so. I have a note here saying "If we have a BSEffectShaderProperty we assume the alpha channel is used whether or not VERTEX_ALPHA is set. Some FO4 meshes seem to work this way" and in fact the FO4 FemaleEyesAO.nif _does_ seem to work that way. So does setting the VERTEX_ALPHA bit cause the exported nif to fail at all?  I'm creating vertex alpha on import and then finding it on export, which is why we get this result.

It's possible that FO4 works this way and Skyrim should not.

It seems this TriShape is exported as a BSTriShape, not a BSLODTriShape, which seems like a worse bug.

And the LightingInfluence problem needs fixing too.

**Comment by michaelsmolinski** [comment]
Got it. Export doesn't fail and no missing BSTriShape nodes. Some errors do show in the blender console. See bottom of this comment.

Regarding BSLODTriShape - Were you referring to a different nif you were looking at? That node type isn't in blackbriar nif that I had attached.

I also noticed the cubemap texture file reference is missing for those windows too (separate node). See images below. Let me know if you want me to post as a separate tracker item.

![screenshot cubemap import](https://github.com/BadDogSkyrim/PyNifly/assets/101998837/6b68074c-cb3f-4cb6-9b69-0bf704c1831c)

![screenshot cubemap export](https://github.com/BadDogSkyrim/PyNifly/assets/101998837/f68ba86e-3775-428e-bace-6757c22323b6)


====================
FYI - these errors show when exporting

_INFO:pynifly:Exporting L2_WindowGlow
WARNING:pynifly:Could not determine shader attributes
WARNING:pynifly:Shader nodes are not set up for export to nif. Check and fix in generated nif file._

_INFO:pynifly:Exporting BlackBriarChalet:7
WARNING:pynifly:Error setting property parallaxInnerLayerTextureScale <- [0.949999988079071, 0.949999988079071]_

I can confirm the 0.95 is in the original nif but not in the exported nif. Let me know if you want me to post as a separate tracker item.

**Comment by BadDogSkyrim** [comment]
It's the LE version of that nif that has the BSLODTriShape nodes. They apparently aren't used in SE.

I might constrain that VERTEX_ALPHA check to FO4 only, just to be conservative.

The shader errors on export are fixed. They don't break anything.

Not sure whatup with the parallaxInnerLayerTextureScale. I didn't see the error in my testing but I'll check.

**Comment by BadDogSkyrim** [comment]
Fixed in latest.
