### ISSUE TITLE
Feature Request: import / export models with (optional?) front facing -Y

### ISSUE THREAD

**Issue by kamicane** [BadDogSkyrim/PyNifly#64]
Right now pynifly imports models with their front facing Y. This is what blender calls back:

![image](https://user-images.githubusercontent.com/7131/133702768-bcd59039-5117-4903-9b4f-d55826ef1afb.png)

This is mostly fine, but the studio / materials lights have to be adjusted, and there are a few symmetry issues with some addons (retopoflow) expecting the front to be the front.

Outfit studio outputs objs the correct way (for blender anyways) while nifskope outputs objs like pynifly.

**Comment by BadDogSkyrim** [comment]
Huh. I've dealt with back being front so long I admit I never thought of doing it a different way. I don't really have any reason why it would be a problem to turn the model around.

**Comment by BadDogSkyrim** [comment]
So I put in a feature to do this and then I pulled it out again because I wasn't happy that I'd thought it through well enough.

- If I import a skinned mesh and say to rotate it to Blender-front, what happens to the armature bones? I assume they get rotated too?
- Does the rotation happen by a transform on the shape or by transforming the vert positions? I'm inclined to say vert positions should never change and the transform should be on the shape.
- How do skinned and unskinned meshes work? Are they different?
- If I import a skinned mesh but have an armature selected, does the skinned mesh match the orientation of the armature? Can I screw it up? Is there any value to that? 
- (Related: If the mesh I'm importing has bone positions that don't match the bone positions of the armature I'm using for a parent, what then? Do I warp the mesh to reflect the parent? Do I parent it and let the positions be wrong, so the mesh is warped on export? Do I ignore the existing armature and create a new one?)
- On export, can the user choose whether to rotate or not? Presumably it should rotate by default on export if it was rotated on import. Do all object have to be rotated or does the armature rule?

If anybody wants to weigh in on all that, do.

**Comment by BadDogSkyrim** [comment]
Implemented with "Use Blender orientation" flag.
