### ISSUE TITLE
Import certain tri file failed

### ISSUE THREAD

**Issue by Heaverno** [BadDogSkyrim/PyNifly#66]
[Downloads.zip](https://github.com/BadDogSkyrim/PyNifly/files/7229053/Downloads.zip)
file is part of Trophihunter's work, which can be easily found on his site.
I can't get "IKAROSBaseFemaleHeadChargen.tri" into Blender but another similar file "BaseFemaleHeadChargen.tri" could.
The console told me if it's corrupted or it's caused by mod auther. 
I believe it's not corrupted on my hand since I've tried from scratch for 2 times and these attempts are several months apart. 
I also wonder if it's caused by mod auther so I've downloaded another mod using the same mesh and it worked, but I'm aware of these tri files differ from size. 
The mod haven't been updated for quiet a time, I wonder if this tri file will work in game cuz I don't have fo4 on my pc right now.
I guess this is not a issue but this is the best place I could find to ask a question :)

**Comment by BadDogSkyrim** [comment]
I'll check it out. Marking as a bug for now.

**Comment by BadDogSkyrim** [comment]
Key piece of the console window (you _did_ look at the console window, right?):

`Number of verticies differs from number of UV coordinates
TRI file has valid header, but file appears to be corrupt
   !! Since 'Base Verticies' != 'UV Coordinates', file is probably corrupt.`

I'll tweak the importer so it imports correctly, but without a UV. Nonetheless, this tri has a problem.

**Comment by BadDogSkyrim** [comment]
Fixed a while back.
